apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-broker
  namespace: enterprise-aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-broker
  template:
    metadata:
      labels:
        app: rabbit-broker
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-broker-svc
  namespace: enterprise-aiops
spec:
  selector:
    app: rabbit-broker
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management
