"""dcs.hats — one module per engineering discipline plus the HATS taxonomy."""

HATS = {
    "FE": "frontend",
    "BE": "backend",
    "FS": "fullstack",
    "MO": "mobile",
    "EMB": "embedded",
    "FW": "firmware",
    "KRN": "kernel",
    "SYS": "systems",
    "DIS": "distributed",
    "NET": "networking",
    "DB": "database",
    "DBA": "dba",
    "DE": "data eng",
    "DS": "data science",
    "MLE": "ml eng",
    "RES": "research",
    "GFX": "graphics",
    "GAME": "game",
    "SHD": "shader",
    "CMP": "compiler",
    "PL": "pl design",
    "FM": "formal",
    "SO": "sec offensive",
    "SD": "sec defensive",
    "CRY": "crypto",
    "RE": "reverse eng",
    "SRE": "sre",
    "DO": "devops",
    "PLT": "platform",
    "CL": "cloud",
    "REL": "release",
    "QA": "qa",
    "AUT": "automation",
    "HPC": "hpc",
    "SCI": "scientific",
    "QT": "quant",
    "ROB": "robotics",
    "SIM": "simulation",
    "CAD": "cad",
    "AU": "audio",
    "VID": "video",
    "TW": "tech writer",
    "DA": "dev advocate",
    "SA": "solutions arch",
    "HW": "hardware",
    "NWE": "net eng",
    "STE": "storage eng",
    "CMP2": "compliance",
}
